### ISSUE TITLE
Uploading while minimized

### ISSUE THREAD

**Issue by eemed** [pqina/filepond#363] opened 2019-08-28 07:18 UTC
### Summary
Files are uploaded REALLY slowly if I drop in more than `maxParallelUploads` files and minimize the browser. I'm not sure if its a filepond issue or are the browsers just throttling the traffic.

### How to reproduce
- Drop in more than `maxParallelUploads` files
- Minimize browser
- Wait
- Open browser and the uploading continues normally

### Expected behaviour
Files are uploaded normally.

### Additional information
Used packages:
```json
    "react-filepond": "^7.0.1",
    "filepond": "^4.4.8",
    "filepond-plugin-file-validate-size": "^2.2.0",
```
My Filepond component;
```js
import React from 'react';
import { FilePond, registerPlugin } from 'react-filepond';
import FilePondPluginFileValidateSize from 'filepond-plugin-file-validate-size';

import MetadataField from './metadata-field';

import 'filepond/dist/filepond.min.css';
import '../styles/dropbox.scss';

registerPlugin(FilePondPluginFileValidateSize);

class Dropbox extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      metadata: '',
    };

    this.onChange = this.onChange.bind(this);
    this.onClick = this.onClick.bind(this);
  }

  onChange(evt) {
    this.setState({ metadata: evt.target.value });
  }

  onClick(evt) {
    evt.preventDefault();
    this.setState({ metadata: '' });
  }

  render() {
    const { metadata } = this.state;
    return (
      <div>
        <p className="crit instructions">The maximum file size is 32GB.</p>
        <p className="instructions">Recommended browser is Chrome.</p>
        <FilePond
          ref={ref => {
            this.pond = ref;
          }}
          allowMultiple
          allowRevert={false}
          dropOnPage
          allowFileSizeValidation
          maxFileSize="34359720775"
          maxParallelUploads={100}
          itemInsertInterval={10}
          onprocessfile={(err, file) => {
            if (!err) {
              setTimeout(() => this.pond.removeFile(file.id), 60000);
            }
          }}
          name="file"
          server={{
            process: {
              url: '/api/upload',
              withCredentials: true,
              headers: {
                metadata: Buffer.from(metadata).toString('base64'),
                'Cache-Control': 'no-cache',
              },
              onerror: res => {
                return res;
              },
            },
          }}
        />
        <MetadataField metadata={metadata} onClick={this.onClick} onChange={this.onChange} />
      </div>
    );
  }
}

export default Dropbox;
```
| Environment  | Version
|------------- | -----------
| OS           |  Windows 10 Enterprise 1809
| Device     | Dell Precision 3510
| Browser      | Chrome 76.0.3809.100, Microsoft Edge 44.17763.1.0

**Comment by rikschennink** [comment] 2019-09-01 11:29
Duplicate of #239

**Closed by rikschennink** 2019-09-01 11:29 UTC
