### ISSUE TITLE
Performance drop when repositioning crop center dynamically

### ISSUE THREAD

**Issue by hennessyevan** [pqina/filepond#349] opened 2019-07-23 18:59 UTC
### Summary

When using a number of plugins together and using the `setImageCropCenter` method from `filepond-plugin-image-crop` memory usage sky rockets to at least 2GB and over 5GB sometimes and has locked up my computer twice.

### How to reproduce

https://codesandbox.io/s/react-filepond-memory-leak-si9wt

### Expected behaviour

It shouldn't eat up so much memory.

### Additional information

I spent quite a few hours in the debugger and the event listener I set up doesn't seem to be called more often than expected. I suspect something is happening in the filepond *ticker* that stacks tons of these events at once although I don't know much about the ticker really.

I'm wondering also if there is a way to get a hold of the `filepond--image-canvas-wrapper` element to update the transform first and then update the cropCenter only after all of that movement?

| Environment  | Version
|------------- | -----------
| OS           | macOS
| Device       |  iMac
| Browser      | Chrome 76, Safari 12

**Comment by rikschennink** [comment] 2019-07-24 07:27
It seemed pretty smooth, not sure if the codesandbox environment has an impact on this. Also, you're calling the method a lot, it's not really intended to be used like this. Still it should work, not sure why it's eating that much memory.

**Comment by hennessyevan** [comment] 2019-07-24 14:09
Yeah it is smooth, I was surprised how easy it was to get up and running, the plugin system here is great. After playing with it for a while though the memory usage really spikes.

I'll keep hacking away and drop my findings here. Off the top of your head is there any way to get access to the transform properties on `filepond--image-canvas-wrapper` from within the plugin system?

**Comment by rikschennink** [comment] 2019-07-25 07:56
@hennessyevan You'd have to fork the preview plugin to be able to modify those. Please keep me posted, I'm a bit busy but I'm of course interested in resolving any memory CPU issues. Wondering if you can reproduce the issue outside of the codesandbox enviroment, with vanilla JavaScript FilePond version (that would also eliminate React, not that I think that is the issue, but the more "clean" the test the better the data).

**Comment by hennessyevan** [comment] 2019-08-15 17:05
Hey @rikschennink I made a reproduction here https://github.com/hennessyevan/filepond-performance-repro it still is happening in a vanilla environment, activity monitor shows this while moving the image around 
![image](https://user-images.githubusercontent.com/16711653/63111981-fdf37c80-bf5c-11e9-94de-eef3951c7e64.png)

After about 2-3minutes the tab crashes and I have to force close it in chrome task manager.

**Comment by rikschennink** [comment] 2019-08-15 17:23
Thanks @hennessyevan will try to take a look at this ASAP

**Comment by rikschennink** [comment] 2019-09-04 07:38
@hennessyevan I've had some time to go over your code. I think you need to debounce the call to `item.setImageCropCenter({ x, y: cropCenterY });`. Currently your pushing it in `requestAnimationFrame` but that will just delay the call to that moment, mouse move will trigger multiple times (can be tens of times) each frame so your calling that method that many times at the start of the frame.

Two things
1. I think you can remove the `requestAnimationFrame` call as FilePond queues DOM updates to the next frame automatically. I think this should already result in improved performance.
2. You need to make sure only one mouse move is used each frame.

**Comment by rikschennink** [comment] 2019-09-04 07:39
I'm happy to discuss further but since the problem most likely originates from the mousemove situation I'll close the issue for now.

**Closed by rikschennink** 2019-09-04 07:39 UTC
Labels: test case needed
