### ISSUE TITLE
stylePanelLayout=circle doesn't work on Chrome

### ISSUE THREAD

**Issue by Keltin42** [pqina/filepond#406] opened 2019-11-05 19:53 UTC
The circle isn't actually a circle.  You can see this in your own demo code here:  https://pqina.nl/filepond/#profile-picture-demo

Here is an example image:
![image](https://user-images.githubusercontent.com/33882419/68240560-04285080-ffc2-11e9-9aa4-4454d6b51b87.png)

I have the exact same problem in my own project, and after spending a ton of time trying to figure it out, I went and checked the example and I see you have the same issue.

On an android mobile device it looks fine until you actually select a picture, and then you just get a square version of the picture.
On an iOS device the image will actually be a circle, but the image is offset to the right in the grey background circle, and slightly differently on phone vs. ipad.

**Comment by rikschennink** [comment] 2019-11-07 07:47
I've tested this on Chrome 78 on MacOS Mojave and Chrome 78 on Windows 10 and cant reproduce it there. As no further info has been supplied I'll close the issue for now.

**Closed by rikschennink** 2019-11-07 07:47 UTC

**Comment by Keltin42** [comment] 2019-11-07 22:11
Interesting.  I checked several machines, and my two Mac's with Chrome 78 have the issue, but the one with 77 does not.  My PC with 78 does not.  I'll assume it is a Chrome bug that will sort itself out.  Thanks!

**Comment by rikschennink** [comment] 2019-11-08 07:12
Very weird, thanks for reporting, I'll keep an eye on it.
