### ISSUE TITLE
Is Filepond down?

### ISSUE THREAD

**Issue by yukyolol** [pqina/filepond#128] opened 2018-10-02 12:17 UTC
Hello, is Filepond down? Everything was working correctly until today.
When the page loads sometimes it doesn't load correctly the uploader or when uploading something no matters what server I'm selecting the uploader keeps rolling the loader and nothing happens.

I'm running the version 3.0.1
I don't see any errors in my code, and I didn't changed anything. The last change was done 2 months ago, and everything until now was working perfectly.

Thanks!

**Comment by rikschennink** [comment] 2018-10-02 12:30
Have you also updates the plug-ins?

I’m not sure what you mean with “down”, the product site seems to function as intended.

**Comment by yukyolol** [comment] 2018-10-02 12:34
This is what i'm using:
```
<link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">
<script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-validate-size/dist/filepond-plugin-image-validate-size.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-crop/dist/filepond-plugin-image-crop.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-resize/dist/filepond-plugin-image-resize.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-transform/dist/filepond-plugin-image-transform.js"></script>
<script src="https://unpkg.com/filepond/dist/filepond.js"></script>
<script src="https://unpkg.com/filestack-js@1.4.1/build/browser/filestack.min.js"></script>
<script src="https://dd7tel2830j4w.cloudfront.net/f1534596466174x344648426165804300/azure-storage.blob.min.js"></script>
```

And:

```
	FilePond.registerPlugin(
  		FilePondPluginFileEncode,
  		FilePondPluginFileValidateType,
  		FilePondPluginFileValidateSize,
  		FilePondPluginImageExifOrientation,
      	FilePondPluginImageCrop,
  		FilePondPluginImagePreview,
      	FilePondPluginImageResize,
  		FilePondPluginImageValidateSize,
      	FilePondPluginImageTransform
	);
```

Does the code changed syntax or something? That I need to update my code?

**Comment by rikschennink** [comment] 2018-10-02 12:47
There are some changes to crop data format so that might be it? 

I would advice to lock to a certain version, instead of auto getting the latest version. You can specify the version in the unpkg url.

**Comment by yukyolol** [comment] 2018-10-02 12:48
I'm planning to use the image editor and remove the old CROP plugin. Will remove now the crop from the code and I will see if the uploader reacts.

Could you give me the locked link to the CURRENT version now? So I can lock the uploader to this current version after replacing the crop.

Thanks.

**Comment by rikschennink** [comment] 2018-10-02 12:53
I’m currently on my phone as my main workstation is updating to Mojave :-)

You can check https://unpkg.com/ how to format the url. Check what the latest version is on GitHub and use that.

It’s somehing like:
https://unpkg.com/filepond@3.0.1/dist/filepond.min.js

**Comment by yukyolol** [comment] 2018-10-02 13:02
Okay thank you, will check it no worries.
One more question, before I remove the old CROP from my code. My plan is to add the new live edit image, but in the doc i don't see the way to register the plugin:

Like this:
```
FilePond.registerPlugin(
  		FilePondPluginFileEncode,
  		FilePondPluginFileValidateType,
  		FilePondPluginFileValidateSize,
  		FilePondPluginImageExifOrientation,
      	        FilePondPluginImageCrop,
  		FilePondPluginImagePreview,
      	        FilePondPluginImageResize,
  		FilePondPluginImageValidateSize,
      	        FilePondPluginImageTransform
	);
```
Thanks.

**Comment by rikschennink** [comment] 2018-10-02 13:06
You can add it to the end of the list. FilePondPluginImageEdit, the file is available in the product page, so you can’t get it from a CDN but will have to upload it to your own server and link it.

It should be in the docs but I see now that I’ve forgotten to add the registerPlugin statement, the other part, script and style embed, of the manual installation section is correct though:
https://pqina.nl/filepond/docs/patterns/plugins/image-edit/

**Comment by yukyolol** [comment] 2018-10-02 13:09
Perfect, before this new changes what was the past version? That is using the OLD crop settings, and has no changes on the code?

Want to keep both versions :dancer:

**Comment by rikschennink** [comment] 2018-10-02 13:17
I think you can set it up like this, with the `^2` to automatically select the previous version:
https://unpkg.com/filepond@^2/dist/filepond.min.js

You can see the latest versions and when they were released in this list:
https://www.npmjs.com/search?q=filepond

So that's 2 for:
- filepond-plugin-image-transform
- filepond-plugin-image-preview
- filepond-plugin-image-resize

And 1 for:
- filepond-plugin-image-crop
- filepond-plugin-file-encode
- filepond-plugin-file-validate-size
- filepond-plugin-file-rename
- filepond-plugin-image-validate-size
- filepond-plugin-image-exif-orientation
- filepond-plugin-file-validate-type
- filepond-plugin-file-metadata
- filepond-plugin-file-poster

**Comment by yukyolol** [comment] 2018-10-02 13:33
Thanks @rikschennink,
I tried with older versions and nothing, when using older version the uploader looks weird and stills not working:
https://imgur.com/a/k1WTeeU

Is there any way to send you my code privately and you can may check if there's any other changes?

Thanks.

**Comment by rikschennink** [comment] 2018-10-02 13:46
Hmm is it possible that the browser might have cached the old CSS files? Have you tried clearing the cache?

If that doesn’t work you can send them to info@pqina.nl

**Comment by yukyolol** [comment] 2018-10-02 14:45
How I can see the plugins older versions?? I believe the problem is that.
What's the correct link to the older version that was using as max 29 august 2018?

```
<link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet">
<script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-validate-size/dist/filepond-plugin-image-validate-size.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-crop/dist/filepond-plugin-image-crop.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-resize/dist/filepond-plugin-image-resize.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-transform/dist/filepond-plugin-image-transform.js"></script>
```

**Comment by rikschennink** [comment] 2018-10-02 15:04
See this reply for the version numbers:
https://github.com/pqina/filepond/issues/128#issuecomment-426269833

You don’t need the specific version, just the major version, add like this: `^2`

**Comment by yukyolol** [comment] 2018-10-02 15:12
Also for the plugins? Like this:
<link href="https://unpkg.com/filepond-plugin-image-preview^2/dist/filepond-plugin-image-preview.css" rel="stylesheet">
<script src="https://unpkg.com/filepond-plugin-image-preview^2/dist/filepond-plugin-image-preview.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-exif-orientation^2/dist/filepond-plugin-image-exif-orientation.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-validate-size^2/dist/filepond-plugin-image-validate-size.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-size^2/dist/filepond-plugin-file-validate-size.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-encode^2/dist/filepond-plugin-file-encode.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-type^2/dist/filepond-plugin-file-validate-type.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-crop^2/dist/filepond-plugin-image-crop.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-resize^2/dist/filepond-plugin-image-resize.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-transform^2/dist/filepond-plugin-image-transform.js"></script>

**Comment by rikschennink** [comment] 2018-10-02 17:35
You forgot the `@` and not all plugins should be at version 2.0, just successfully tested the following should work:

```html
<link href="https://unpkg.com/filepond@^2/dist/filepond.css" rel="stylesheet">
<link href="https://unpkg.com/filepond-plugin-image-preview@^2/dist/filepond-plugin-image-preview.css" rel="stylesheet">

<script src="https://unpkg.com/filepond@^2/dist/filepond.js"></script>

<script src="https://unpkg.com/filepond-plugin-image-exif-orientation@^1/dist/filepond-plugin-image-exif-orientation.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-validate-size@^1/dist/filepond-plugin-image-validate-size.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-size@^1/dist/filepond-plugin-file-validate-size.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-encode@^1/dist/filepond-plugin-file-encode.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-type@^1/dist/filepond-plugin-file-validate-type.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-crop@^1/dist/filepond-plugin-image-crop.js"></script>

<script src="https://unpkg.com/filepond-plugin-image-preview@^2/dist/filepond-plugin-image-preview.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-resize@^2/dist/filepond-plugin-image-resize.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-transform@^2/dist/filepond-plugin-image-transform.js"></script>
```

**Closed** 2018-10-03 00:34 UTC
