### ISSUE TITLE
Uploaded files not properly Exif orientated

### ISSUE THREAD

**Issue by Yericus** [pqina/filepond#322] opened 2019-05-24 12:58 UTC
Hi,

I am not sure why but I can not manage to get filepond to upload a transformed file with the proper exif orientation.

The preview is working as expected, alas no matter what i do the uploaded file is always missing the proper orientation.

I am really turning crazy, the metadata file generated returns the orientation of the picture taken.
The resizing is applied all right but the exif correction is not applied.

This is probably not the right place to come for help so feel free to delete this.
But any pointers should the answer be an obvious thing would be most welcome.

Thanks for an amazing module that is filepond.

```html
<input type="file" class="filepond" accept="image/png, image/jpeg">
		
<!-- Load FilePond library -->
<script src="https://unpkg.com/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"></script>
<script src="https://unpkg.com/filepond-plugin-file-rename/dist/filepond-plugin-file-rename.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-resize/dist/filepond-plugin-image-resize.js"></script>
<script src="https://unpkg.com/filepond-plugin-image-transform/dist/filepond-plugin-image-transform.js"></script>
<script src="https://unpkg.com/filepond/dist/filepond.js"></script>

<script>
FilePond.registerPlugin(FilePondPluginImageExifOrientation,FilePondPluginFileValidateType,FilePondPluginFileRename,FilePondPluginImagePreview,FilePondPluginImageResize,FilePondPluginImageTransform);
 
const inputElement = document.querySelector('input[type="file"]');

const pond = FilePond.create(inputElement, {
	labelIdle: `<span class="filepond--label-action" style="padding: 0px ; margin: 0px">Take animal picture</span>`,
	imageResizeTargetWidth: 800,
	imageTransformOutputMimeType: 'image/jpeg',
	imageTransformOutputQuality: 85,
	imagePreviewHeight: 350,
	}
);

FilePond.setOptions({
	server: 'filepond/',
        fileRenameFunction: (file) => {
		return `tmp_patient${file.extension}`;
		}
	})
</script>
```

**Comment by rikschennink** [comment] 2019-05-24 13:13
Hi, so sorry, it turns out version `3.3.0` of the plugin had a bug that would prevent application of the exif orientation info. Fixed now in version `3.3.1`.

**Comment by Yericus** [comment] 2019-05-24 15:34
You are the man.

**Comment by Yericus** [comment] 2019-05-24 15:51
Manually installed the 3.3.1 version of the plug in and it worked !
My brain thanks you after some hours of obsessing about that ahah.
Peace for sleep it is !

**Comment by rikschennink** [comment] 2019-05-24 17:07
Fantastic, thanks for confirming it works!

**Closed by rikschennink** 2019-05-24 17:07 UTC
Labels: bug

**Comment by chintanp** [comment] 2020-04-11 01:47
@rikschennink This does not seem to be working for me. I am getting the correct preview in the browser, but the image orientation on the server is not the same. I am using: Filepond (v4.13.1), and FilePondPluginImageExifOrientation (v1.0.6). 

The relevant code is as below: 

```javascript
FilePond.registerPlugin(
    // corrects mobile image orientation
    FilePondPluginImageExifOrientation,
    // encodes the file as base64 data
    FilePondPluginFileEncode,
    // validates the size of the file
    FilePondPluginFileValidateSize,
    FilePondPluginFileValidateType, // validate type
    // previews dropped images
    FilePondPluginImagePreview
);

// Select the file input and use create() to turn it into a pondd
FilePond.create(
    document.querySelector('input[type="file"]'), {
    acceptedFileTypes: ['image/*'],
    allowImageExifOrientation: true,
    allowFileEncode: false,
    ....
```

Any suggestions on how I can debug this?

**Comment by rikschennink** [comment] 2020-04-11 07:29
@chintanp which device and os version are you testing with?

**Comment by chintanp** [comment] 2020-04-11 08:02
@rikschennink I have seen uploads from Android (OnePlus 7) and iOS (some iPhone) both not oriented right.

**Comment by rikschennink** [comment] 2020-04-11 09:10
Which OS versions?

There seem to be issues with iOS 13.4 but I need more info

**Comment by chintanp** [comment] 2020-04-11 19:51
@rikschennink sorry about the delay in response. 

OS tested so far: Android 10 & iPhone iOS 13.3.1.

**Comment by rikschennink** [comment] 2020-04-12 07:35
I don’t see the image transform plugin in the register list, it’s needed to apply the changed.

**Comment by chintanp** [comment] 2020-04-12 19:16
@rikschennink In my latest attempt, I am using the following code:

```javascript
FilePond.registerPlugin(
    // corrects mobile image orientation
    FilePondPluginImageExifOrientation,
    // encodes the file as base64 data
    FilePondPluginFileEncode,
    // validates the size of the file
    FilePondPluginFileValidateSize,
    FilePondPluginFileValidateType, // validate type
    // previews dropped images
    FilePondPluginImagePreview,
    FilePondPluginImageResize,
    FilePondPluginImageTransform
);

// Select the file input and use create() to turn it into a pondd
FilePond.create(
    document.querySelector('input[type="file"]'), {
    acceptedFileTypes: ['image/*'],
    allowImageExifOrientation: true,
    imageCropAspectRatio: '1:1',
    imageResizeTargetWidth: 300,
    imageResizeTargetHeight: 300,
    imageResizeMode: 'cover',
    instantUpload: true,
    imageTransformOutputQuality: 85,
    allowFileEncode: false,
    server: {
```

with the aim of the additional functionality of resizing before upload. This solves the EXIF orientation issue on my Android (10) and an iPad (iOS 12.x, Chrome and Safari) I tested on. **However, it seems to not work on Chrome (81.0) on Android 10**.  I wonder if it is related to this issue of Chrome (https://stackoverflow.com/questions/42401203/chrome-image-exif-orienation-issue) but then this does work fine Chrome on iOS, so this is perplexing. Any suggestions on how to debug this?

**Comment by rikschennink** [comment] 2020-04-14 14:00
@chintanp Note that it's high on my todolist to look into this. In the mean time, Chrome on iOS is secretly just Safari so that would explain why it works fine on iOS.

**Comment by chintanp** [comment] 2020-04-14 18:01
@rikschennink also, I found the orientation is not an issue on all Chrome/Anndroids I tested, the three others I tested worked fine.

**Comment by rikschennink** [comment] 2020-04-15 08:59
@chintanp I've found the issue, fixing it now.

**Comment by rikschennink** [comment] 2020-04-15 09:19
@chintanp Should be fixed if you update the image exif orientation plugin to latest version `1.0.7`, please confirm.

**Comment by chintanp** [comment] 2020-04-15 19:50
@rikschennink Thanks a lot for your prompt support. Works now on Chrome and Firefox in my Android as well as Chrome and Safari on my iPad. I Will update if I find an issue elsewhere.

**Comment by rikschennink** [comment] 2020-04-16 06:15
@chintanp fantastic 👍

**Comment by chintanp** [comment] 2020-05-09 21:26
@rikschennink apparently there is another modality where the uploaded exif image is not properly oriented. 

Please see the video: 
![size-reduction-cropped_5kYVkFWG_SiHP](https://user-images.githubusercontent.com/752869/81484865-ffa55480-91fd-11ea-8bbf-166876e55d9c.gif)

for the image: (apparently incorrectly oriented on Github too)

![image2](https://user-images.githubusercontent.com/752869/81485118-a0484400-91ff-11ea-8727-f91d568a8b9f.JPG)


When we resize a pre-shot image in iPhone before uploading, apparently it is not properly oriented. 
iOS 13.3.1 / iPhone 11 Pro Max. Browser either Chrome/Safari. 

Another minor issue is the image size numbers, we see some inconsistency between the actual size, the size reported by the file selection box and size finally displayed in the filepond (could also be affected by the resize operation). But below is the operation of Exif properly oriented when size is not changed by the iOS resizer. 

![actual-size-photo_rNEVcoxZ_0eXS](https://user-images.githubusercontent.com/752869/81485252-8e1ad580-9200-11ea-9f09-f24c18139f2e.gif)

 and the associated image: (also incorrectly oriented on Github)

![image1](https://user-images.githubusercontent.com/752869/81485176-eb625700-91ff-11ea-82af-ed424f2f64ca.JPG)

**Comment by rikschennink** [comment] 2020-05-10 12:34
Size is what the browser reports, it's probably different because I believe iOS internally uses a different image format.

Are all plugins updated to the latest version? If so, if you can provide a test case on codesandbox.io that would be helpful.

**Comment by chintanp** [comment] 2020-05-11 22:04
@rikschennink The issue also exists in the react-filepond and this existing codesandbox had the orientation issue on image resize https://codesandbox.io/s/rylk9z5lzm. 

This also exists in the filepond exif orientation demo plugin: https://pqina.github.io/filepond-plugin-image-exif-orientation/ as be seen in this video. 


![RPReplay_Final1589153029(1)_Trim](https://user-images.githubusercontent.com/752869/81616532-7bd39f80-9398-11ea-8f3a-533efa677e2e.gif)

**Comment by rikschennink** [comment] 2020-05-12 06:32
@chintanp the codesandbox demo is still on older versions of the plugins. If you update it it should work correctly.

I can't reproduce the issue on the other demo, tried chrome and safari with all kinds of images that have orientation information, but they all showed correct. Can you make sure the cache is cleared?

**Comment by chintanp** [comment] 2020-05-12 19:06
I updated the codesandbox with latest libraries (https://codesandbox.io/s/qbh57). Filepond 4.13.6 and exif-orientation 1.0.8, image-preview 4.6.2 and the issue exists in this demo as well as the image-exif demo here: https://pqina.github.io/filepond-plugin-image-exif-orientation/ 

The issue to specific to image resize inside iPhone (i.e. this resize is not due to filepond, but it is an iPhone feature) before uploading (the videos show how to achieve this). So the issue can be attributed to an iPhone abnormality.

**Comment by rikschennink** [comment] 2020-05-13 08:50
@chintanp okay, now I understand the issue. 

The problem occurs when the image is resized in iOS, interesting. I created a new issue in the exif orientation repo.

https://github.com/pqina/filepond-plugin-image-exif-orientation/issues/7

**Comment by rikschennink** [comment] 2020-05-13 14:12
After some research it seems this is indeed the problem:

> So the issue can be attributed to an iPhone abnormality.
