### ISSUE TITLE
Filepond element is been displayed at the top of the page

### ISSUE THREAD

**Issue by anandutk** [pqina/filepond#232] opened 2019-02-14 04:15 UTC
Hi There! When I was trying to use Filepond in my Laravel application, I encountered a really weird issue, i.e. the input tag with filepond integration is been displayed at the top of the page, and also two different file inputs tags are being displayed. I thought it was because  `querySelector` had `(input` in it. But if I'm trying to use a class as `querySelector` , it's not working. 

**In fact, if I'm trying to upload a file without filepond, it's working fine** 

Thanks in advance!

**Comment by rikschennink** [comment] 2019-02-14 06:43
This sounds like the stylesheet is not loaded?

Without any further information, it's difficult to determine what is going on.

Please note that without using the file-encode plugin you can't use FilePond (or any other drag n drop file upload solution) to post files along with a classic form post. 

> When we want to submit files along with the classic form post we run into a serious browser limitation. The file input field is the only field available to submit files to a server but its value cannot be set. The file input field value can only be modified by the user by manually adding files (in one action).

**Comment by anandutk** [comment] 2019-02-14 15:37
Every file is working... Let me share screenshots...

![screenshot 2019-02-14 at 9 02 45 pm](https://user-images.githubusercontent.com/13445904/52797505-0a754600-309c-11e9-86d8-29eb994b3c82.png)


And code...

![screenshot 2019-02-14 at 9 04 46 pm](https://user-images.githubusercontent.com/13445904/52797705-6cce4680-309c-11e9-9e6c-66416bed7b8d.png)


And plugins...

![screenshot 2019-02-14 at 9 05 56 pm](https://user-images.githubusercontent.com/13445904/52797725-75bf1800-309c-11e9-88b3-a3f5122d180d.png)

**Comment by rikschennink** [comment] 2019-02-15 05:36
It’s not clear to me what the problem is, please elaborate

**Comment by anandutk** [comment] 2019-02-15 07:12
As you can see, the `<input type="file">` is not above "description", and "title". But still, it's shown on the top. And there's only one "input file" tag is present in the code, here it's displaying tow of them.

**Comment by rikschennink** [comment] 2019-02-15 07:18
You're selecting `input`, there's a good chance the framework you're using injects hidden input fields at the top of the form.

```js
FilePond.create(
    document.querySelector('.filepond')
}
```

Also, the `div` next to the `<input type="file">` is an opening `div` but it's not closed, this could result in other issues. Please make sure your [HTML is valid](https://validator.w3.org).

**Comment by anandutk** [comment] 2019-02-15 08:13
I've tried this earlier also, but it's not been able to send the image to DB.

**Comment by rikschennink** [comment] 2019-02-15 08:16
It seems like the form is posted using a classic form post, that's why I added this in my first reply:

> When we want to submit files along with the classic form post we run into a serious browser limitation. The file input field is the only field available to submit files to a server but its value cannot be set. The file input field value can only be modified by the user by manually adding files (in one action).

You're either going to have to upload the files async or upload using the file encode plugin

**Comment by anandutk** [comment] 2019-02-15 08:28
As you told me to include encode, I've been getting new type of error

![screenshot 2019-02-15 at 1 57 08 pm](https://user-images.githubusercontent.com/13445904/52844048-b87b0180-3129-11e9-88f8-0287cfbf45cb.png)

**Comment by rikschennink** [comment] 2019-02-15 08:59
These errors are not related to FilePond but are related to the framework you're using.

**Comment by anandutk** [comment] 2019-02-15 09:04
Yes, but these errors are not coming when I'm not using filepond.

**Comment by rikschennink** [comment] 2019-02-15 09:12
Yes, but as you're now encoding the file as a base64 string your form validation can't validate it (as the string is not a file object), so you'll have to either remove the validation or adjust the validation logic.

**Comment by anandutk** [comment] 2019-02-15 09:19
Which validation are you saying to remove, filepond's or one on laravel's side???

**Comment by rikschennink** [comment] 2019-02-15 09:22
The validations that you highlighted are on Laravel's side

**Comment by anandutk** [comment] 2019-02-15 09:37
After removing the validation, it's updating the database, but still unable to send the image

**Comment by rikschennink** [comment] 2019-02-15 09:39
See this documentation entry for the file format set by the file encode plugin, your server will have to turn it back into a file object.
https://pqina.nl/filepond/docs/patterns/plugins/file-encode/

**Comment by rikschennink** [comment] 2019-02-15 09:45
I'm going to close this now, as the original issue has been resolved.

**Closed by rikschennink** 2019-02-15 09:45 UTC
