### ISSUE TITLE
Error "Ruleset ignored due to bad selector" in Firefox

### ISSUE THREAD

**Issue by andreasklostermaier** [pqina/filepond#657] opened 2021-02-12 09:32 UTC
**Describe the bug**

Loading a page in Firefox (85.0.1), with filepond active, produces two errors of type "Ruleset ignored due to bad selector."
The error messages seem to not affect the correct performance of FilePond (therefore low prio).

**Logs**

Ruleset ignored due to bad selector. filepond.css:656:45
Ruleset ignored due to bad selector. filepond.css:660:45

**To Reproduce**

The error messages only show up in Firefox (cannot see them in Brave/Vivaldi).
The error messages only show up, if a manual install of "filepond.css" was performed (Version: FilePond 4.25.1).
Loading "filepond.css" from the CDN does NOT produce the error messages.

**Expected behavior**

No error messages should be produced by "filepond.css"

**Stacktraces**

The affected lines in "filepond.css" are:

.filepond--list-scroller::-webkit-scrollbar:vertical {
  width: 1em;
}

.filepond--list-scroller::-webkit-scrollbar:horizontal {
  height: 0;
}

**Information about your project:**

- Firefox 85.0.1
- Ubuntu Linux 20.10
- FilePond version 4.25.1

**Comment by rikschennink** [comment] 2021-02-12 09:46
These are selectors prefixed so they target other browsers. Firefox chooses to show a warning about this. Closed because won't fix and is not a bug.

**Closed by rikschennink** 2021-02-12 09:46 UTC
Labels: wontfix
