### ISSUE TITLE
Grid not wrapping fixed width items properly

### ISSUE THREAD

**Issue by tomdav999** [pqina/filepond#653] opened 2021-02-05 09:21 UTC
I am using fixed width for filepond items: 

.filepond--item {
    width: 200px;
}

Depending on container width, the last item will overflow instead of wrapping properly to the next row.  I believe the problem is the use of Math.round instead of Math.floor:

var itemsPerRow = Math.round(horizontalSpace / itemWidth);

**Comment by rikschennink** [comment] 2021-02-08 14:28
We require the issue template to be filled out on all new issues. The issue template helps us collect all the information we need to address your submission efficiently.

The more information we have, the faster the issue can be resolved.

We will be able to more closely look at your issue once the issue template has been filled out. The issue will be closed until the above is addressed. Please leave a comment after you've updated the issue.

**Comment by tomdav999** [comment] 2021-02-20 22:59
**Describe the bug**

When filepond items have fixed width (for grid view)  the last item in the row will overflow and not wrap properly if it consumes more than 50% of remaining container width.

**Logs**

n/a

**To Reproduce**

Set item width to 200px (see OP). 

1) Set container width to 320px. Add 2 images.  Second image will overflow instead of wrapping.

2) Set container width to 300px.  Add 2 images.  Second image will wrap properly and not overflow.

**Expected behavior**

In both cases second image should wrap instead of overflow.

**Additional context**

See OP for bug fix.

**Comment by rikschennink** [comment] 2021-03-08 14:32
Should be fixed in https://github.com/pqina/filepond/releases/tag/4.25.2

Please close when confirmed.

**Comment by rikschennink** [comment] 2021-03-19 12:05
Closed because inactive

**Closed by rikschennink** 2021-03-19 12:05 UTC
Labels: bug
