### ISSUE TITLE
Aborting a chunked upload does not revert

### ISSUE THREAD

**Issue by maxmitti** [pqina/filepond#755] opened 2021-08-19 14:27 UTC
**Describe the bug**

When using chunked uploads and aborting an upload no revert is sent and the patch files are left on the server.
As can be seen in the screenshot below the client does not send any request after canceling the current chunk.
The client definitely knows the file id already.

**Logs**

![Screenshot_20210819_161906](https://user-images.githubusercontent.com/12127872/130085034-9a115e51-73f2-455e-a149-3dc41b50d358.png)

**To Reproduce**

My setup is based on [filepond-boilerplate-php](https://github.com/pqina/filepond-boilerplate-php).

I configured FilePond as follows:
```
// Set default FilePond options
FilePond.setOptions({
        // upload to this server end point
        server: './api',
        chunkUploads: true
});

// Turn a file input into a file pond
var pond = FilePond.create(document.querySelector('input[type="file"]'));
```

Removing already finished uploads works correctly.

**Expected behavior**

After canceling the currently uploading chunk request I would expect FilePond to send a revert request in order to remove the already uploaded chunk files.

**Information about your project:**

- Your browser and the version: Chromium Version 92.0.4515.131 (Official Build) Arch Linux (64-bit)
- Your operating system: Arch Linux
- FilePond version 4.28.2

**Comment by rikschennink** [comment] 2021-08-20 17:53
I think this is a duplicate of https://github.com/pqina/filepond/issues/433

will close for now

**Closed by rikschennink** 2021-08-20 17:53 UTC

**Comment by maxmitti** [comment] 2021-08-20 19:34
Oh, right.
Sorry, I got a bit confused because sometimes it was mentioned that it affects downloads which failed after some chunks.
But if it also addresses still running uploads then this is a duplicate.

**Comment by rikschennink** [comment] 2021-08-21 14:37
No worries :) I'm trying to keep things organised but I'm super busy so if you feel it's a separate thing then let me know and I'll re-open. All good.

About PR: Would super appreciate that, I believe I unfortunately couldn't merge it because I had to revert another change.
