### ISSUE TITLE
MSEdge Browser is not able to delete the file entry after upload is complete

### ISSUE THREAD

**Issue by SaltyG13z** [pqina/filepond#308] opened 2019-04-24 21:36 UTC
Hello fellow developer!

### Summary
MSEdge Browser is not able to delete the file entry after upload is complete
...

### How to reproduce
1. Use Microsof Edge to connect to  https://pqina.nl/filepond/#examples
2. Use File Explorer and to select a .jpg file from any directory on you hard disk (Do not use Browse)
3. Click and Drag the file from your directory to the Drag & Drop filepond--drop-label area
4. Wait for the file upload to complete
5. Click on the X Link to remove the file entry
...

### Expected behavior
Clicking on the X Link doen not remove the file entry when using MSEdgeea
...

### Additional information
Chrome works correctly

###Workaround:  Use MSEdge to Upload the same file a second time.  The X link is able to remove the entry or entries 
...

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows 10
| Device       | PC
| Browser      | Microsoft Edge 41.16299.1004.0

**Comment by rikschennink** [comment] 2019-04-26 14:51
I just tested this with Edge 18 on Windows 10 (44.17763.1.0) but can't reproduce the issue. Clicking the X removes the file correctly from the files list, tried with both zip and jpeg.

**Comment by SaltyG13z** [comment] 2019-04-29 13:20
I used jpg and png files.  The problem can be intermittent.  Also - use a file that has never been used before.  This seems to have some cache setting.   Also noticed the X seems to not be enabled when the issue occurs.  If you mouse over the X the mouse does not highlight the component.  Will add video if I can

**Comment by SaltyG13z** [comment] 2019-04-29 13:43
![ProblemEdge](https://user-images.githubusercontent.com/34565657/56900063-f1f1b680-6a62-11e9-9c5f-e5359a43671a.png)
![Reports](https://user-images.githubusercontent.com/34565657/56900174-31200780-6a63-11e9-81b3-35d7e638c219.jpeg)

**Comment by SaltyG13z** [comment] 2019-04-29 13:43
Use the attached jpeg.  Seems to happen on new files that have never been used

**Comment by rikschennink** [comment] 2019-04-30 07:08
Tried with the supplied file + Windows 10 + Edge 17 + Drop. Cannot reproduce the problem.

**Comment by SaltyG13z** [comment] 2019-04-30 08:06
Sorry to hear that.  Out of curiosity, can you try it from another PC.  I'll do the same here.

**Comment by rikschennink** [comment] 2019-04-30 09:18
I've tried this on Browserstack, with multiple instances, and a colleague of mine has tried it on his machine.

**Comment by rikschennink** [comment] 2019-05-02 06:06
Will close this until it can be reproduced

**Closed by rikschennink** 2019-05-02 06:06 UTC
Labels: cannot reproduce

**Comment by SaltyG13z** [comment] 2019-05-02 10:59
no problem.  Maybe its a problem with my machine only.  You are correct I am not able to reproduce on other machines.

Thanks

-sal
